config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  get 'cocktails/newdesign', to: 'cocktails#newdesign'
  resources :ingredients
  resources :cocktails do
    resources :doses, only: %i[new create show destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true
  validates :name, presence: true

  mount_uploader :image, ImageUploader

  def list_doses
    doses.map { |dose| dose.ingredient.name }.join(', ')
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
  validates :description, :ingredient, :cocktail, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update delete]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def newdesign
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @doses = Dose.all
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def delete
    @cocktail.delete
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image, :image_cache)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @doses = Dose.all
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <%= render 'shared/cocktail_form' %>
  <hr>

  <%= link_to "Back to Cocktail Overview", cocktails_path  %>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1185434/pexels-photo-1185434.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260);">
  <div class="container">
    <h1>David's Cocktail Bar</h1>
    <p>Checkout all our Cocktails</p>
  </div>
</div>
<div class="container">
  <h1>Cocktail Overview</h1>

  <% @cocktails.each do |cocktail| %>
  <div class="card-product">
    <%= cl_image_tag cocktail.image, crop: :fill %>
    <div class="card-infos">
      <div class="card-product-infos text-capitalize">
        <h2><%= cocktail.name %></h2>
          <p><%= cocktail.list_doses %>
          </p>
        </div>
      <div class="options">
        <%= link_to cocktail_path(cocktail) do  %>
        <button class="btn btn-success">See Ingredients</button>
        <% end %>
        <%= link_to edit_cocktail_path(cocktail) do %>
        <button class="btn btn-primary">Edit</button>
        <% end %>
        <%= link_to cocktail_path(cocktail), method:"delete" do  %>
        <button class="btn btn-danger">Delete</button>
        <% end %>
      </div>
    </div>
    </div>
    <% end %>
    <hr>
    <h2>Create New Cocktail</h2>
    <%= render 'shared/cocktail_form' %>
  </div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<div class="container">
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/newdesign.html.erb
<div class="container">
  <h1>Some Overview</h1>
  <div class="hrcard">
    <% @models.each do |model| %>
    <div class="hrcard-product">
      <img src=<%= model.image_url %>>
      <div class="hrcard-content">
        <div class="hrcard-product-infos text-capitalize">
          <h2><%= link_to model_path(model) do  %>
            <%= model.name %>
            <% end %>
            <p><%= model.list_details %>
            </p>
          </div>
          <div class="options">
            <%= link_to edit_model_path(model) do %>
            <button class="btn btn-outline-primary">Edit</button>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.image, crop: :fill %>');">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>Checkout all ingredients</p>
  </div>
</div>
<div class="container">

  <div class="list-group">
    <% @cocktail.doses.each do |dose| %>
    <div class="list-group-item card-infos" style="height:100px;">
        <div class="content">
          <%= dose.description %> - <%= dose.ingredient.name.capitalize %>
        </div>
        <div class="options">
          <%= link_to cocktail_dose_path(@cocktail, dose), method:"delete" do %>
          <button class="btn btn-danger btn-sm circle">x</button>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
  <h2>Add New Ingredient</h2>

  <%= render 'doses/new', cocktail: @cocktail, dose: @dose %>


  <hr>

  <%= link_to "Back to Cocktail Overview", cocktails_path  %>
</div>

<%=  javascript_pack_tag "select2" %>
</div>

app/views/doses/_new.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit class:"btn btn-primary" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>David's Cocktail Bar</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <%= javascript_pack_tag "application" , defer: true%>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/shared/_banner.html.erb
_banner.html.erb

app/views/shared/_card.html.erb
<div class="card-product">
  <img src=<%= image_url %>>
  <div class="card-product-infos">
    <h2><%= link_to cocktail_path(cocktail) do  %>
      <%= title %>
      <% end %><%= title %></h2>
    <p><%= content %></p>
  </div>
</div>

app/views/shared/_cocktail_form.html.erb
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.submit class:"btn btn-primary" %>
    <% end %>